language: c

before_install:
  - sudo apt update
  - sudo apt install cmake
  - sudo apt-get install valgrind

before_script:
  - pip3 install --user cpplint


script:
  - cppcheck main.c
  - cppcheck Resource.h
  - cpplint main.c
  - cpplint Resource.h
  - g++ -g -Wall -Wextra main.c -o main
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .

after_script:
  - make clean

addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
      - "cppcheck"
    update: true
